### ISSUE TITLE
Can't start main.go using v0.1.1

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#720]
## Bug Report

I can't launch main.go as it reports such prometheus or servicecatalog issues

Project : https://github.com/snowdrop/component-operator/blob/operator-0.1.1/cmd/component-operator/main.go#L59

```
OPERATOR_NAME=component-operator WATCH_NAMESPACE=my-spring-app KUBERNETES_CONFIG=$HOME/.kube/config go run cmd/component-operator/main.go
# github.com/snowdrop/component-operator/vendor/github.com/coreos/prometheus-operator/pkg/client/monitoring/v1
vendor/github.com/coreos/prometheus-operator/pkg/client/monitoring/v1/alertmanager.go:58:44: undefined: dynamic.Client
vendor/github.com/coreos/prometheus-operator/pkg/client/monitoring/v1/client.go:101:17: undefined: dynamic.Client
# github.com/snowdrop/component-operator/vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1
vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1/register.go:72:36: not enough arguments in call to scheme.AddFieldLabelConversionFunc
        have (schema.GroupVersionKind, func(string, string) (string, string, error))
        want (string, string, runtime.FieldLabelConversionFunc)
vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1/register.go:73:36: not enough arguments in call to scheme.AddFieldLabelConversionFunc
        have (schema.GroupVersionKind, func(string, string) (string, string, error))
        want (string, string, runtime.FieldLabelConversionFunc)
vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1/register.go:74:36: not enough arguments in call to scheme.AddFieldLabelConversionFunc
        have (schema.GroupVersionKind, func(string, string) (string, string, error))
        want (string, string, runtime.FieldLabelConversionFunc)
vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1/register.go:75:36: not enough arguments in call to scheme.AddFieldLabelConversionFunc
        have (schema.GroupVersionKind, func(string, string) (string, string, error))
        want (string, string, runtime.FieldLabelConversionFunc)
vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1/register.go:76:36: not enough arguments in call to scheme.AddFieldLabelConversionFunc
        have (schema.GroupVersionKind, func(string, string) (string, string, error))
        want (string, string, runtime.FieldLabelConversionFunc)
vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1/register.go:77:36: not enough arguments in call to scheme.AddFieldLabelConversionFunc
        have (schema.GroupVersionKind, func(string, string) (string, string, error))
        want (string, string, runtime.FieldLabelConversionFunc)
vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go:39:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go:44:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go:49:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go:54:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go:54:13: too many errors
```

Questions :

- Is there a version of k8s servicecatalog which is working with operator-sdk as 0.1.37 reports the error mentioned ?
- What is the version of prometheus-core to be defined as dependency ?

**Comment by AlexNPavel** [comment]
It looks like the `scheme.AddLabelConversionFunc` function has changed from 1.11 -> 1.12 and now requires different arguments. This is the change: https://github.com/kubernetes-incubator/service-catalog/commit/ff7f8a073416e82e7065972ac9f19c6806d3e6a3#diff-6f555a2a1b3ea5d792e9aedf19e45bb3. You would probably have to use a version before that commit to fix the service catalog issue until we upgrade to kubernetes 1.12.

For the prometheus operator issues, I'm not quite sure why that's having issues. It looks like it should work. Maybe somebody else can help figure that out.

**Comment by estroz** [comment]
@cmoulliard can you try running `dep ensure` and try to reproduce your error? I pulled your operator repo, ran `make build` without issue, and did not see the same errors when running your posted command. Thanks!

**Comment by cmoulliard** [comment]
I was able to resolve the dep issue of prometheus by adding this dep to the tom file. Can you add it to `operator-sdk` code generator's please ?
```
[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "0.24.0"
```

**Comment by cmoulliard** [comment]
From the reading of the `dep ensure -v` output, it looks like that the latest version of the service-catalog is used `0.1.38` and which is responsible of the problem. I will update my toml file to avoid to take this latest version but instead `0.1.30`

**Comment by LiliC** [comment]
@cmoulliard Did that solve your problem?

**Comment by cmoulliard** [comment]
Yes. If you then add this dependency within the code generated by the operator-sdk, then the ticket could be closed

```
[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "0.24.0"
```

**Comment by shawn-hurley** [comment]
@cmoulliard I am not seeing this problem when you create a new operator with the sdk. This leads me to believe that the reason you had to override this was due to some other dependencies that you brought in. I do not believe that the SDK should be setting an override for a dependacy that it does not need.

**Comment by LiliC** [comment]
Yes up to now it didn't need that, something happened in the latest release of the `prometheus-operator` that broke dep when I was versioning. But I suspect you @cmoulliard stumbled upon this due to one of his dependencies not our sdk as you do not seem to use the metrics helpers in the project. 

In any case I pined to that release of the operator in this PR https://github.com/operator-framework/operator-sdk/pull/715 as we need that from now on. Closing this for now.
