### ISSUE TITLE
operator-sdk add api --api-version=app.example.com/v1alpha1 --kind=AppService

### ISSUE THREAD

**Issue by l10xbin** [operator-framework/operator-sdk#1428]
## Bug Report

**What did you do?**
Try to generate api with command `operator-sdk add api --api-version=app.example.com/v1alpha1 --kind=AppService`

**What did you expect to see?**
End with no error.

**What did you see instead? Under which circumstances?**
operator-sdk add api --api-version=app.example.com/v1alpha1 --kind=AppService
INFO[0000] Generating api version app.example.com/v1alpha1 for kind AppService.
INFO[0000] Created pkg/apis/app/v1alpha1/appservice_types.go
INFO[0000] Created pkg/apis/addtoscheme_app_v1alpha1.go
INFO[0000] Created pkg/apis/app/v1alpha1/register.go
INFO[0000] Created pkg/apis/app/v1alpha1/doc.go
INFO[0000] Created deploy/crds/app_v1alpha1_appservice_cr.yaml
W0515 01:49:17.315998    9049 parse.go:239] Ignoring child directory github.com/l10xbin/app-operator/pkg/apis/app: unable to import "github.com/l10xbin/app-operator/pkg/apis/app": go/build: importGo github.com/l10xbin/app-operator/pkg/apis/app: exit status 1
go: finding github.com/l10xbin/app-operator/pkg/apis/app latest
go: finding github.com/l10xbin/app-operator/pkg/apis latest
go: finding github.com/l10xbin/app-operator/pkg latest
can't load package: package github.com/l10xbin/app-operator/pkg/apis/app: unknown import path "github.com/l10xbin/app-operator/pkg/apis/app": cannot find module providing package github.com/l10xbin/app-operator/pkg/apis/app

INFO[0009] Created deploy/crds/app_v1alpha1_appservice_crd.yaml
Error: exit status 2
Usage:
  operator-sdk add api [flags]

Flags:
      --api-version string   Kubernetes APIVersion that has a format of $GROUP_NAME/$VERSION (e.g app.example.com/v1alpha1)
  -h, --help                 help for api
      --kind string          Kubernetes resource Kind name. (e.g AppService)

Global Flags:
      --verbose   Enable verbose logging

**Environment**
* operator-sdk version:

  operator-sdk version: v0.7.0+git
* go version:

go version go1.11.2 linux/amd64
* Kubernetes version information:
  noting to do with kube

* Kubernetes cluster kind: 
  nothing to do with kube cluster
* Are you writing your operator in ansible, helm, or go?
  go
**Possible Solution**

**Additional context**

**Comment by l10xbin** [comment]
It looks like the problem of go mod, After upgrade go version from 1.11 to go version go1.12.5 linux/amd64, The command works.
